/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VectorKit.framework/VectorKit
 */

@interface VKMercatorTerrainHeightCache : NSObject {
    struct map<md::Anchor *, float, std::__1::less<md::Anchor *>, std::__1::allocator<std::__1::pair<md::Anchor *const, float> > > { 
        struct __tree<std::__1::__value_type<md::Anchor *, float>, std::__1::__map_value_compare<md::Anchor *, std::__1::__value_type<md::Anchor *, float>, std::__1::less<md::Anchor *>, true>, std::__1::allocator<std::__1::__value_type<md::Anchor *, float> > > { 
            struct __tree_node<std::__1::__value_type<md::Anchor *, float>, void *> {} *__begin_node_; 
            struct __compressed_pair<std::__1::__tree_end_node<std::__1::__tree_node_base<void *> *>, std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<md::Anchor *, float>, void *> > > { 
                struct __tree_end_node<std::__1::__tree_node_base<void *> *> { 
                    struct __tree_node_base<void *> {} *__left_; 
                } __first_; 
            } __pair1_; 
            struct __compressed_pair<unsigned long, std::__1::__map_value_compare<md::Anchor *, std::__1::__value_type<md::Anchor *, float>, std::__1::less<md::Anchor *>, true> > { 
                unsigned long long __first_; 
            } __pair3_; 
        } __tree_; 
    }  _anchorToHeight;
    <VKMercatorTerrainHeightProvider> * _heightProvider;
}

@property (nonatomic) <VKMercatorTerrainHeightProvider> *heightProvider;

- (id).cxx_construct;
- (void).cxx_destruct;
- (double)heightForAnchor:(struct Anchor { int (**x1)(); struct Mercator3<double> { double x_2_1_1[3]; } x2; struct Coordinate2D<Degrees, double> { struct Unit<DegreeUnitDescription, double> { double x_1_2_1; } x_3_1_1; struct Unit<DegreeUnitDescription, double> { double x_2_2_1; } x_3_1_2; } x3; id x4; /* Warning: Unrecognized filer type: '' using 'void*' */ void*x5; void*x6; void*x7; void*x8; void*x9; void*x10; void*x11; void*x12; void*x13; void*x14; void*x15; void*x16; void*x17; void*x18; long doublex19; void*x20; void*x21; void*x22; void*x23; void*x24; void*x25; void*x26; void*x27; void*x28; void*x29; void*x30; void*x31; void*x32; void*x33; const void*x34; void*x35; void*x36; void*x37; void*x38; void*x39; void*x40; long x41; void*x42; SEL x43; void*x44; SEL x45; void*x46; long doublex47; void*x48; void*x49; void*x50; void x51; void*x52; int x53; void*x54; BOOL x55; void*x56; void*x57; void*x58; void*x59; void*x60; void*x61; void*x62; struct x63; void*x64; void*x65; void*x66; short x67; void*x68; void*x69; void*x70; const void*x71; void*x72; void*x73; BOOL x74; void*x75; void*x76; void*x77; void*x78; void*x79; long doublex80; void*x81; void*x82; void*x83; void x84; void*x85; int x86; void*x87; BOOL x88; void*x89; void*x90; void*x91; void*x92; void*x93; struct x94; void*x95; }*)arg1;
- (id)heightProvider;
- (void)invalidateRect:(const struct Box<double, 2> { struct Matrix<double, 2, 1> { double x_1_1_1[2]; } x1; struct Matrix<double, 2, 1> { double x_2_1_1[2]; } x2; }*)arg1;
- (void)removeCachedValueForAnchor:(struct Anchor { int (**x1)(); struct Mercator3<double> { double x_2_1_1[3]; } x2; struct Coordinate2D<Degrees, double> { struct Unit<DegreeUnitDescription, double> { double x_1_2_1; } x_3_1_1; struct Unit<DegreeUnitDescription, double> { double x_2_2_1; } x_3_1_2; } x3; id x4; /* Warning: Unrecognized filer type: '' using 'void*' */ void*x5; void*x6; void*x7; void*x8; void*x9; void*x10; void*x11; void*x12; void*x13; void*x14; void*x15; void*x16; void*x17; void*x18; long doublex19; void*x20; void*x21; void*x22; void*x23; void*x24; void*x25; void*x26; void*x27; void*x28; void*x29; void*x30; void*x31; void*x32; void*x33; void*x34; const void*x35; void*x36; const out void*x37; void*x38; void*x39; void*x40; SEL x41; union { BOOL x_42_1_1; out in short x_42_1_2; void*x_42_1_3; void*x_42_1_4; short x_42_1_5; void*x_42_1_6; const void*x_42_1_7; BOOL x_42_1_8; void*x_42_1_9; void*x_42_1_10; oneway void*x_42_1_11; void*x_42_1_12; int x_42_1_13; long x_42_1_14; void*x_42_1_15; void*x_42_1_16; void*x_42_1_17; void*x_42_1_18; void*x_42_1_19; struct  unsigned int x1; int x2; int x3; unsigned int x4;  {} x_42_1_20; char *x_42_1_21; } x42; void*x43; const void*x44; void*x45; void*x46; void*x47; short x48; void*x49; void*x50; void*x51; void*x52; void*x53; const void*x54; void*x55; void*x56; double x57; void*x58; void*x59; void*x60; void*x61; void*x62; void*x63; void*x64; void*x65; void*x66; void*x67; void*x68; void*x69; void*x70; BOOL x71; void*x72; out void*x73; void*x74; void*x75; in void*x76; void*x77; void*x78; void*x79; void*x80; struct x81; void*x82; }*)arg1;
- (void)setHeightProvider:(id)arg1;

@end
