/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSCH3DGetSelectionKnobsPositionsRenderProcessor : TSCH3DTransformGeometryRenderProcessor {
    float  mNormalizedKnobRadius;
    NSMutableArray * mProjectedPoints;
    TSCH3DGetSelectionKnobsPositionsPipelineDelegate * mSceneObjectDelegate;
}

@property (nonatomic) float normalizedKnobRadius;
@property (nonatomic, retain) NSMutableArray *projectedPoints;
@property (nonatomic, retain) TSCH3DGetSelectionKnobsPositionsPipelineDelegate *sceneObjectDelegate;

- (void)dealloc;
- (struct tmat4x4<float> { struct tvec4<float> { union { float x_1_2_1; float x_1_2_2; float x_1_2_3; } x_1_1_1; union { float x_2_2_1; float x_2_2_2; float x_2_2_3; } x_1_1_2; union { float x_3_2_1; float x_3_2_2; float x_3_2_3; } x_1_1_3; union { float x_4_2_1; float x_4_2_2; float x_4_2_3; } x_1_1_4; } x1[4]; })modelViewNormalizedProjection;
- (float)normalizedKnobRadius;
- (id)projectedPoints;
- (id)sceneObjectDelegate;
- (void)setNormalizedKnobRadius:(float)arg1;
- (void)setProjectedPoints:(id)arg1;
- (void)setSceneObjectDelegate:(id)arg1;
- (void)submit:(const struct PrimitiveInfo { int x1; int x2; int x3; id x4; /* Warning: Unrecognized filer type: '' using 'void*' */ void*x5; void*x6; void*x7; void*x8; void*x9; void*x10; void*x11; void*x12; void*x13; long long x14; bool x15; void*x16; void*x17; void*x18; void*x19; void*x20; void*x21; void*x22; void*x23; void*x24; void*x25; void*x26; void*x27; void*x28; void*x29; void*x30; void*x31; void*x32; unsigned char x33; unsigned char x34; void*x35; const int x36; double x37; oneway int x38; void*x39; void*x40; unsigned char x41; out in void*x42; const out long x43; long x44; void*x45; const void*x46; void*x47; void*x48; void*x49; void*x50; void*x51; void*x52; void*x53; void*x54; void*x55; void*x56; void*x57; long doublex58; void*x59; void*x60; void*x61; void*x62; void*x63; void*x64; void*x65; void x66; void*x67; void*x68; void*x69; void*x70; void x71; void*x72; void*x73; void*x74; BOOL x75; void*x76; void*x77; void*x78; void*x79; void*x80; int x81; void*x82; in void*x83; void*x84; void*x85; void*x86; void*x87; void*x88; void*x89; struct x90; void*x91; }*)arg1;

@end
