/* Generated by RuntimeBrowser.
 */

@protocol TSCH3DRenderBufferAllocator <NSObject>

@required

- (id)colorbufferWithAllocatorInfo:(const struct RenderbufferAllocatorInfo { struct FramebufferAttributes {} *x1; struct tvec2<int> {} *x2; id x3; /* Warning: Unrecognized filer type: '1' using 'void*' */ void*x4; void*x5; void*x6; void*x7; void*x8; void*x9; void*x10; void*x11; char *x12; void*x13; void*x14; void*x15; id x16; void*x17; void*x18; void*x19; void*x20; void*x21; void*x22; void*x23; void*x24; BOOL x25; void*x26; void*x27; void*x28; out void*x29; const void*x30; void*x31; void*x32; void*x33; void*x34; struct x35; void*x36; void*x37; void*x38; float x39; void*x40; long x41; void*x42; out void*x43; void*x44; void*x45; void*x46; void*x47; void*x48; void*x49; void*x50; void*x51; void*x52; void*x53; void*x54; void*x55; void*x56; void*x57; float x58; void*x59; long x60; void*x61; out void*x62; void*x63; void*x64; void*x65; void*x66; void*x67; void*x68; void*x69; void*x70; void*x71; void*x72; void*x73; void*x74; void*x75; void*x76; float x77; void*x78; long x79; void*x80; out void*x81; void*x82; void*x83; void*x84; void*x85; void*x86; void*x87; void*x88; void*x89; void*x90; void*x91; void*x92; void*x93; void*x94; void*x95; }*)arg1;
- (id)depthbufferWithAllocatorInfo:(const struct RenderbufferAllocatorInfo { struct FramebufferAttributes {} *x1; struct tvec2<int> {} *x2; id x3; /* Warning: Unrecognized filer type: '1' using 'void*' */ void*x4; void*x5; void*x6; void*x7; void*x8; void*x9; void*x10; void*x11; char *x12; void*x13; void*x14; void*x15; void*x16; void*x17; void*x18; void*x19; void*x20; void*x21; void*x22; void*x23; struct x24; void*x25; void*x26; void*x27; float x28; void*x29; long x30; void*x31; out void*x32; void*x33; void*x34; void*x35; void*x36; void*x37; void*x38; void*x39; void*x40; void*x41; void*x42; void*x43; void*x44; void*x45; void*x46; float x47; void*x48; long x49; void*x50; out void*x51; void*x52; void*x53; void*x54; void*x55; void*x56; void*x57; void*x58; void*x59; void*x60; void*x61; void*x62; void*x63; void*x64; void*x65; float x66; void*x67; long x68; void*x69; out void*x70; void*x71; void*x72; void*x73; void*x74; void*x75; void*x76; void*x77; void*x78; void*x79; void*x80; void*x81; void*x82; void*x83; void*x84; }*)arg1;
- (bool)isTexturable;

@end
