/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NanoTimeKitCompanion.framework/NanoTimeKitCompanion
 */

@interface NTKEnumeratedEditOption : NTKEditOption {
    unsigned long long  _value;
}

+ (id)_localizedNameForValue:(unsigned long long)arg1;
+ (id)_nameLocalizationKeyForValue:(unsigned long long)arg1;
+ (id)_optionWithValue:(unsigned long long)arg1;
+ (id)_orderedValues;
+ (id)_orderedValuesRestrictedByCurrentDeviceCollection;
+ (id)_snapshotKeyForValue:(unsigned long long)arg1;
+ (bool)_valueIsValid:(unsigned long long)arg1;
+ (unsigned long long)indexOfOption:(id)arg1;
+ (unsigned long long)numberOfOptions;
+ (id)optionAtIndex:(unsigned long long)arg1;
+ (id)optionsRestrictedByCurrentDeviceCollection;
+ (bool)supportsSecureCoding;

- (id)JSONObjectRepresentation;
- (id)_faceBundleStringToValueDict;
- (unsigned long long)_value;
- (id)_valueToFaceBundleStringDict;
- (id)dailySnapshotKey;
- (void)encodeWithCoder:(id)arg1;
- (unsigned long long)hash;
- (id)initWithCoder:(id)arg1;
- (id)initWithJSONObjectRepresentation:(id)arg1;
- (bool)isEqual:(id)arg1;
- (bool)isValidOption;
- (id)localizedName;

@end
