/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NanoTimeKitCompanion.framework/NanoTimeKitCompanion
 */

@interface NTKFaceColorNumeralsAnalogEditOption : NTKFaceColorEditOption

+ (id)_localizedNameForValue:(unsigned long long)arg1;

@end
