/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NanoTimeKitCompanion.framework/NanoTimeKitCompanion
 */

@interface NTKFaceColorModularEditOption : NTKFaceColorEditOption

+ (id)_orderedValues;

@end
