/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NanoTimeKitCompanion.framework/NanoTimeKitCompanion
 */

@interface NTKMickeyCharacterColorEditOption : NTKCharacterColorEditOption

+ (id)_orderedValues;
+ (id)optionWithFaceColor:(unsigned long long)arg1;
+ (id)optionWithOption:(id)arg1;

@end
