/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NanoTimeKitCompanion.framework/NanoTimeKitCompanion
 */

@interface NTKMinnieCharacterColorEditOption : NTKCharacterColorEditOption

+ (id)_orderedValues;
+ (id)optionWithFaceColor:(unsigned long long)arg1;

@end
