/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Celestial.framework/Celestial
 */

@interface AVFileValidator : NSObject {
    struct AVFileValidatorPrivate { id x1; struct FigOpaqueMediaValidator {} *x2; struct FigMediaValidatorDataLocation { unsigned long long x_3_1_1; unsigned long long x_3_1_2; } x3; struct OpaqueCMByteStream {} *x4; bool x5; bool x6; id x7; /* Warning: Unrecognized filer type: '' using 'void*' */ void*x8; void*x9; void*x10; void*x11; void*x12; void*x13; void*x14; void*x15; void*x16; void*x17; void*x18; void*x19; void*x20; void*x21; void*x22; void*x23; void*x24; void*x25; void*x26; char *x27; void*x28; void*x29; void*x30; void*x31; void*x32; void*x33; void*x34; void*x35; void*x36; void*x37; void*x38; void*x39; void*x40; float x41; void*x42; void*x43; void*x44; void*x45; void*x46; const void*x47; void*x48; void*x49; void*x50; void*x51; void*x52; void*x53; void*x54; void*x55; SEL x56; void*x57; SEL x58; void*x59; unsigned short x60; void*x61; void*x62; void*x63; const void*x64; int x65; void*x66; in void*x67; void*x68; void*x69; unsigned int x70; void*x71; void*x72; void*x73; void*x74; void*x75; long x76; void*x77; void*x78; void*x79; void*x80; void*x81; struct x82; void*x83; void*x84; void*x85; short x86; void*x87; void*x88; void*x89; const void*x90; void*x91; void*x92; BOOL x93; void*x94; void*x95; void*x96; void*x97; void*x98; unsigned short x99; void*x100; void*x101; void*x102; const void*x103; int x104; void*x105; in void*x106; void*x107; void*x108; unsigned int x109; void*x110; void*x111; void*x112; void*x113; void*x114; long x115; void*x116; void*x117; void*x118; struct x119; void*x120; } * _priv;
    NSString * _validationRules;
}

@property (retain) NSString *validationRules;

- (void)cancel;
- (void)dealloc;
- (id)initWithURL:(id)arg1;
- (id)initWithURL:(id)arg1 options:(id)arg2;
- (bool)isCompleted;
- (bool)isStreaming;
- (id)notificationForFileCheckResult:(id)arg1;
- (void)postNotificationForCallback:(id)arg1;
- (float)progress;
- (void)setValidationRules:(id)arg1;
- (id)url;
- (void)validate;
- (id)validateBlocking:(bool)arg1;
- (void)validateForCameraRoll;
- (bool)validateSyncWithError:(id*)arg1;
- (id)validationRules;

@end
